### ISSUE TITLE
checkpoint_required

### ISSUE THREAD

**Issue by el-lsan** [mmjee/instagram-story-robot#9]
Recently I started to get the following error:
FYI It doesn't happen all the time, so If I run the script again it will succeed eventually!
any idea what is causing this?

```
IgResponseError: GET /api/v1/feed/user/1932777209/story/?.... - 400 Bad Request; checkpoint_required
at Request.handleResponseError (/Users/test/Documents/GitHub/instagram-story-robot/node_modules/instagram-private-api/dist/core/request.js:126:16)
at Request.send (/Users/test/Documents/GitHub/instagram-story-robot/node_modules/instagram-private-api/dist/core/request.js:54:28)
at async UserStoryFeed.request (/Users/test/Documents/GitHub/instagram-story-robot/node_modules/instagram-private-api/dist/feeds/user-story.feed.js:14:26)
at async InstagramManagement.scrapeStories (/Users/test/Documents/GitHub/instagram-story-robot/isr/instagram/index.js:53:5)
at async /Users/test/Documents/GitHub/instagram-story-robot/isr/main.js:54:5
at async Promise.all (index 0)
at async executeScrape (/Users/test/Documents/GitHub/instagram-story-robot/isr/main.js:29:3)
at async main (/Users/test/Documents/GitHub/instagram-story-robot/isr/main.js:75:5)
```

**Comment by mmjee** [comment]
AFAIK this is a very common recurring error due to Instagram needing clients to solve a challenge. 

See: https://github.com/dilame/instagram-private-api/issues/547

Anyway I need to update the dependencies, maybe that'll solve it.

P.S.: Sorry for the delayed reply, GitHub somehow doesn't send me emails for issues created on my repos.

**Comment by mmjee** [comment]
Upgraded packages, see if it reproduces. I'll look into it further if it reproduces.

**Comment by el-lsan** [comment]
Thanks for the update.
I just pulled the changes, however on my second attempt running the script, I've got the error again!

```
user@MacBook-Pro instagram-story-robot % node index.js
info: Logged into Instagram. {"service":"isr","timestamp":"2022-03-04T10:36:25.516Z"}
info: Instagram initialized! {"service":"isr","timestamp":"2022-03-04T10:36:25.518Z"}
info: Started scraping {"service":"isr","timestamp":"2022-03-04T10:36:25.518Z","username":"cristiano"}
info: Done scraping {"service":"isr","timestamp":"2022-03-04T10:36:26.819Z","username":"cristiano"}
^C
user@MacBook-Pro instagram-story-robot % node index.js
info: Logged into Instagram. {"service":"isr","timestamp":"2022-03-04T10:36:33.918Z"}
info: Instagram initialized! {"service":"isr","timestamp":"2022-03-04T10:36:33.921Z"}
info: Started scraping {"service":"isr","timestamp":"2022-03-04T10:36:33.921Z","username":"cristiano"}
IgResponseError: GET /api/v1/feed/user/1932777209/story/?supported_capabilities_new=%5B%7B%22name%22%3A%22SUPPORTED_SDK_VERSIONS%22%2C%22value%22%3A%2213.0%2C14.0%2C15.0%2C16.0%2C17.0%2C18.0%2C19.0%2C20.0%2C21.0%2C22.0%2C23.0%2C24.0%2C25.0%2C26.0%2C27.0%2C28.0%2C29.0%2C30.0%2C31.0%2C32.0%2C33.0%2C34.0%2C35.0%2C36.0%2C37.0%2C38.0%2C39.0%2C40.0%2C41.0%2C42.0%2C43.0%2C44.0%2C45.0%2C46.0%2C47.0%2C48.0%2C49.0%2C50.0%2C51.0%2C52.0%2C53.0%2C54.0%2C55.0%2C56.0%2C57.0%2C58.0%2C59.0%2C60.0%2C61.0%2C62.0%2C63.0%2C64.0%2C65.0%2C66.0%22%7D%2C%7B%22name%22%3A%22FACE_TRACKER_VERSION%22%2C%22value%22%3A12%7D%2C%7B%22name%22%3A%22segmentation%22%2C%22value%22%3A%22segmentation_enabled%22%7D%2C%7B%22name%22%3A%22COMPRESSION%22%2C%22value%22%3A%22ETC2_COMPRESSION%22%7D%2C%7B%22name%22%3A%22world_tracker%22%2C%22value%22%3A%22world_tracker_enabled%22%7D%2C%7B%22name%22%3A%22gyroscope%22%2C%22value%22%3A%22gyroscope_enabled%22%7D%5D - 400 Bad Request; checkpoint_required
at Request.handleResponseError (/Users/user/Documents/GitHub/instagram-story-robot/node_modules/instagram-private-api/dist/core/request.js:126:16)
at Request.send (/Users/user/Documents/GitHub/instagram-story-robot/node_modules/instagram-private-api/dist/core/request.js:54:28)
at async UserStoryFeed.request (/Users/user/Documents/GitHub/instagram-story-robot/node_modules/instagram-private-api/dist/feeds/user-story.feed.js:14:26)
at async InstagramManagement.scrapeStories (/Users/user/Documents/GitHub/instagram-story-robot/isr/instagram/index.js:53:5)
at async /Users/user/Documents/GitHub/instagram-story-robot/isr/main.js:54:5
at async Promise.all (index 0)
at async executeScrape (/Users/user/Documents/GitHub/instagram-story-robot/isr/main.js:29:3)
at async main (/Users/user/Documents/GitHub/instagram-story-robot/isr/main.js:75:5)

```

**Comment by mmjee** [comment]
That's weird, I don't think I can do anything about this, just seems to be Facebook unilaterally requiring CAPTCHA. You can check around the instagram-private-api issues for similar issues and workarounds. If you are using a VPN that might be the principal reason.

Regards,

**Comment by mmjee** [comment]
Also do note you need to rerun `yarn install` or `npm install` after pulling it in, I'm assuming you did that.

Regards,

**Comment by el-lsan** [comment]
Yeah, I did install the modules again and No I don't use VPN. 
It's the same environment and same IP, but I'm getting this error randomly on some tries.
Thanks for looking into this anyway.
I'll dig in more on `instagram-private-api` Repo.
Also thanks for sharing your script 🙌

**Comment by mmjee** [comment]
I hope you find a solution to the issue though. If you do find a solution don't forget to share.

Keeping this issue closed.
Regards,
